messagePool = [
    "...zdejmij kaganiec...",
    "...wylacz telewizje...",
    "...włącz myslenie...",
    "...kim jestes...?",
    "...dlaczego...?",
    "...kiedy bylo jutro...?",
    "...zachodzace słonce reprezentuje smierc...",
    "...kruci...",
    "...w dol..",
    "...wc_s4??...",
    "UNAUTHORISED BRAIN CHIP ACCESS",
    "...lubie majonez Kielecki",
    "...to by nic nie dalo...",
    "...macie moze jeszcze ta kolke...?",
    "...o nie...",
    "...jak...?",
    "...lipinki luzyckie...",
    "...straz pozarna jedzie...",
    "...teraz mnie wszystko boli...",
    "...obudz sie...",
    "...walizka...",
    "...WALIZKA...",
    "...znalezc walizke...",
    "...coraz bardziej...",
    "...hesoyam...",
    "...",
    "...tur tur, tur...",
    "...nie...",
    "...aktywuj system Windows...",
    "...golimar...",
    "...elektroniki, informatyki...",
    "...od Kether do Malkuth...",
    "...od stacji do stacji...",
    "...za późno..."
]